GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "jafar",
    "number": ""
}

###

GET http://localhost:3001/api/persons/64d2e1c1f556820533a2b5cb